# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "pot-kettle-black"
longtitle: "pot-kettle-black is a theme"

# A description of your site for meta tag, search engine results.
description: "pot-kettle-black is Jekyll theme based on Scriptor by Just Good Themes"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://iterative.co.nz"

# Favicon
favicon: images/favicon.png

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Archive
    url: /tags/


# Colors
accent_color: '#e76f51'

# Site footer
footer:
  content: "&copy; Just Good Themes and Joe Mahoney all rights reserved."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
